# Generated by Django 5.2.1 on 2025-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='screenshot',
            field=models.URLField(blank=True, null=True),
        ),
    ]
