# Generated by Django 5.2.1 on 2025-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_informe_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscricion',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
