# Generated by Django 5.2.1 on 2025-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_plan_stripe_price_id_subscricion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('free', 'Free'), ('standar', 'Standar'), ('pro', 'Pro'), ('admin', 'Administrador')], default='free', max_length=10),
        ),
    ]
